version: '3.8'
services:
  astro-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: my-astro-dev:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    restart: "no"